"""M5: events (range-partitioned by ts, monthly)

`events` is a canonical table from CLAUDE.md. It is declared PARTITIONED from
the outset — retrofitting partitioning onto a 50M-row table is a migration
nobody wants to write, and retention becomes an instant DROP instead of a bulk
DELETE that locks and bloats.

Because PostgreSQL requires every unique constraint on a partitioned table to
include the partition key, the primary key is (id, ts) and dedup uniqueness is
(dedup_key, ts) rather than dedup_key alone.

Revision ID: 0004_m5_events
Revises: 0003_m4_sensor
Create Date: 2026-09-14
"""
from __future__ import annotations

from datetime import date, timedelta
from typing import Sequence, Union

import sqlalchemy as sa
from alembic import op
from sqlalchemy.dialects import postgresql

revision: str = "0004_m5_events"
down_revision: Union[str, None] = "0003_m4_sensor"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def _month_start(value: date) -> date:
    return value.replace(day=1)


def _next_month(value: date) -> date:
    return (_month_start(value) + timedelta(days=32)).replace(day=1)


def upgrade() -> None:
    bind = op.get_bind()

    event_type = postgresql.ENUM(
        "alert", "flow", "dns", "http", "tls", name="event_type", create_type=False
    )
    severity = postgresql.ENUM(
        "critical", "high", "medium", "low", "info", name="event_severity", create_type=False
    )
    for enum_type in (event_type, severity):
        enum_type.create(bind, checkfirst=True)

    # Alembic's create_table cannot express PARTITION BY, so this is raw DDL.
    op.execute(
        """
        CREATE TABLE events (
            id            bigint GENERATED BY DEFAULT AS IDENTITY,
            ts            timestamptz NOT NULL,
            ingested_at   timestamptz NOT NULL DEFAULT now(),
            event_type    event_type NOT NULL,
            src_ip        inet,
            dst_ip        inet,
            src_port      integer,
            dst_port      integer,
            proto         varchar(8),
            signature     text,
            signature_id  bigint,
            rev           integer,
            category      varchar(128),
            severity      event_severity NOT NULL DEFAULT 'info',
            src_asset_id  uuid REFERENCES assets(id) ON DELETE SET NULL,
            dst_asset_id  uuid REFERENCES assets(id) ON DELETE SET NULL,
            flow_id       bigint,
            dedup_key     bytea NOT NULL,
            raw           jsonb NOT NULL,
            CONSTRAINT pk_events PRIMARY KEY (id, ts),
            CONSTRAINT uq_events_dedup UNIQUE (dedup_key, ts)
        ) PARTITION BY RANGE (ts)
        """
    )

    # (ts DESC) is the primary read path for M6; the rest support pivoting on
    # an IP or signature during an investigation.
    op.execute("CREATE INDEX ix_events_ts ON events (ts DESC)")
    op.execute("CREATE INDEX ix_events_src_ip_ts ON events (src_ip, ts DESC)")
    op.execute("CREATE INDEX ix_events_dst_ip_ts ON events (dst_ip, ts DESC)")
    op.execute("CREATE INDEX ix_events_signature_id_ts ON events (signature_id, ts DESC)")
    op.execute("CREATE INDEX ix_events_severity_ts ON events (severity, ts DESC)")
    op.execute("CREATE INDEX ix_events_flow_id ON events (flow_id)")
    # No GIN on `raw` yet: it is expensive to maintain and M6 has not measured
    # whether it is needed. Add it there, with numbers.

    # Seed the current month plus two ahead so inserts work immediately; the
    # worker keeps the window topped up from then on.
    cursor = _month_start(date.today())
    for _ in range(3):
        end = _next_month(cursor)
        op.execute(
            f"""
            CREATE TABLE IF NOT EXISTS events_p{cursor.year:04d}{cursor.month:02d}
            PARTITION OF events
            FOR VALUES FROM ('{cursor.isoformat()}') TO ('{end.isoformat()}')
            """
        )
        cursor = end


def downgrade() -> None:
    # Dropping the parent drops every partition with it.
    op.execute("DROP TABLE IF EXISTS events CASCADE")

    bind = op.get_bind()
    for enum_name in ("event_severity", "event_type"):
        postgresql.ENUM(name=enum_name).drop(bind, checkfirst=True)
